name: Build
on:
   push:
      branches:
         - main
jobs:
   build:
      runs-on: self-hosted
      steps:
         - name: Getting models
           run: wget https://storage.yandexcloud.net/traffic-accident-bucket/models.tar.gz && tar -xvf models.tar.gz
         - run: mv ml-models/* models/
         - name: Set up QEMU
           uses: docker/setup-qemu-action@v2
         - name: Log in to Docker Hub
           uses: docker/login-action@v3
           with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2
         - name: Build and push
           uses: docker/build-push-action@v3
           with:
              file: Dockerfile
              push: true
              tags: jsink/personal-account-backend:latest
              build-args: |
                 SERVER_HOST=${{ secrets.SERVER_HOST }}
                 SERVER_PORT=${{ secrets.SERVER_PORT }}
                 IS_PROD=${{ secrets.IS_PROD }}

   deploy:
      needs: build
      runs-on: self-hosted
      steps:
         - name: Remove old docker container
           run: docker stop /traffic-accident-backend-ml && docker rm /traffic-accident-backend-ml
         - if: always()
           name: Pull image and rename from docker hub
           run: docker pull jsink/personal-account-backend:latest && docker image tag
              jsink/personal-account-backend:latest traffic-accident-backend-ml
         - if: always()
           name: Run docker container
           run: docker run --name traffic-accident-backend-ml --restart=always -d -p ${{ secrets.SERVER_PORT }}:5000 traffic-accident-backend-ml
